spring.application.name=stock-controller

file.upload-dir=uploads


# mysql
spring.datasource.url=jdbc:mysql://localhost:3306/stock-control-spring?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true